// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Abitizer
{
    public partial class AbitizerMLModel
    {
        /// <summary>
        /// model input class for AbitizerMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Certificate")]
            public float Certificate { get; set; }

            [ColumnName(@"Ukrainian")]
            public float Ukrainian { get; set; }

            [ColumnName(@"Math")]
            public float Math { get; set; }

            [ColumnName(@"History")]
            public float History { get; set; }

            [ColumnName(@"Geography")]
            public float Geography { get; set; }

            [ColumnName(@"English")]
            public float English { get; set; }

            [ColumnName(@"OtherForeignLang")]
            public float OtherForeignLang { get; set; }

            [ColumnName(@"Physics")]
            public float Physics { get; set; }

            [ColumnName(@"Biology")]
            public float Biology { get; set; }

            [ColumnName(@"Chemistry")]
            public float Chemistry { get; set; }

            [ColumnName(@"UniverSpec")]
            public string UniverSpec { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for AbitizerMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Certificate")]
            public float Certificate { get; set; }

            [ColumnName(@"Ukrainian")]
            public float Ukrainian { get; set; }

            [ColumnName(@"Math")]
            public float Math { get; set; }

            [ColumnName(@"History")]
            public float History { get; set; }

            [ColumnName(@"Geography")]
            public float Geography { get; set; }

            [ColumnName(@"English")]
            public float English { get; set; }

            [ColumnName(@"OtherForeignLang")]
            public float OtherForeignLang { get; set; }

            [ColumnName(@"Physics")]
            public float Physics { get; set; }

            [ColumnName(@"Biology")]
            public float Biology { get; set; }

            [ColumnName(@"Chemistry")]
            public float Chemistry { get; set; }

            [ColumnName(@"UniverSpec")]
            public uint UniverSpec { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AbitizerMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
